# environment.yml
name: jira_chatbot_env
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - spacy
  - transformers
  - nltk
  - scikit-learn
  - pytorch
  - sentence-transformers
  - textblob